services:
    login_listener:
        class: Cms\UserBundle\Service\LoginListener
        arguments: ['@security.context', '@doctrine', '@session']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
