cms_settings:
    resource: "@CmsSettingsBundle/Resources/config/routing.yml"
    prefix:   /

cms_content:
    resource: "@CmsContentBundle/Resources/config/routing.yml"
    prefix:   /

cms_util:
    resource: "@CmsUtilBundle/Resources/config/routing.yml"
    prefix:   /

cms_user:
    resource: "@CmsUserBundle/Resources/config/routing.yml"
    prefix:   /

login_check:
    pattern:   /login_check

logout:
    pattern: /logout

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"